### PR TITLE
Exclude leading and trailing whitespace from `implicit_string`

### LINKED ISSUE #22: Don't include space in right-hand side of context
I think something to do with this line:

https://github.com/wenkokke/tree-sitter-talon/blob/af5d7988181edb6bc257939f6eb11df6630b95ff/grammar.js#L65

Basically the `right` field of `match` includes the space after the `:` in eg `tags: user.foo`

### PR DESCRIPTION
**Pull request by AndreasArvidsson**
Fixes #22

### CODE REVIEW

**Comment by wenkokke** [comment]
Fixes #22.

**Comment by wenkokke** [comment]
Thanks, @AndreasArvidsson! I'll try and publish a release as soon as possible. 

(There's some cruft ill-advisedly on main I'll have to cut out first.)

**Comment by AndreasArvidsson** [comment]
Nice, thank you :)

**Comment by pokey** [comment]
Would it be safe for us to just use version on main branch?  I see that CI is failing, so maybe not?

**Comment by wenkokke** [comment]
Wouldn't recommend it, sorry.

**Pull request merged**
