### PR TITLE
Exclude carriage return from comment nodes.

### LINKED ISSUE #36: Comment node includes trailing `\r`
When using CRLF line endings comments will include a trailing `\r`

```talon
# hello
foo: "bar"
```

node.text: `# hello\r`

### PR DESCRIPTION
**Pull request by wolfmanstout**
Fixes #36

### CODE REVIEW

**Comment by wolfmanstout** [comment]
One thing that was surprising (to me) about the Mocha unit tests: I have to run "npm install" *twice* to reliably rebuild after grammar changes (you can bet I found out the hard way, after nearly tearing my hair out). This is because npm install rebuilds the bindings based on binding.gyp as its first step, before parser.c is regenerated (which is a dependency of the bindings). If someone who is more familiar with npm and/or tree-sitter knows if there's a better way, that would be helpful. Otherwise this might be worth documenting.

**Comment by wolfmanstout** [comment]
I fixed the aforementioned issue (following tree-sitter-python here).

**Comment by wenkokke** [comment]
Thanks!

Any reason for choosing Mocha?

**Comment by wolfmanstout** [comment]
I saw Cursorless uses it 😂

I'm new to Node.js so no strong preference. I see that the most recent version of Node.js released this year has a native lightweight framework we could also use. Not sure if tooling support is as good, and means people would need recent Node to run tests, though.

**Comment by wenkokke** [comment]
Let's not depend on the latest version.

For now, I'd suggest jest?

**Comment by wenkokke** [comment]
Paging @pokey: Why Mocha over Jest?

**Comment by wenkokke** [comment]
Should make a note that if we add a testing framework, we should port the current JS tests to it.

**Comment by pokey** [comment]
Yeah we'd prob be using jest if it weren't for mocha being default framework for VSCode tests

**Comment by wolfmanstout** [comment]
No problem, I can switch to Jest. Any reason for the preference? Just curious for my own education.

**Comment by wenkokke** [comment]
1. I know how to use it.
2. It's more widely used.
3. It's a little simpler.

**Comment by wolfmanstout** [comment]
Updated to use Jest, ready for review.

**Comment by wolfmanstout** [comment]
Any questions? Feel free to ping me on Slack.

**Comment by wenkokke** [comment]
This is now merged. Sorry for the delay!

**Pull request merged**
