### PR TITLE
Fix CRLF issues by moving parsing from scanner.cc to grammar.js

### LINKED ISSUE #41: Files with CRLF line endings trigger many parse errors
On Windows, the default line ending is CRLF instead of LF. This works fine with Talon, but is not properly parsed by tree-sitter-talon, as discovered in https://github.com/cursorless-dev/cursorless/issues/1950.

The easiest way to reproduce this is to change test/corpus/basic.txt to use CRLF instead of LF line endings (can easily be done with the toggle in VSCode on the bottom right). Rerun tests and you will get many failures.

### PR DESCRIPTION
**Pull request by wolfmanstout**
This simplifies scanner.cc by handling more parsing in grammar.js, and in doing so it fixes at least one bug in scanner.cc. In doing so, it does affect parse output slightly: in particular it omits the "matches" node if the matches section is missing (in line with tree-sitter norms) and comments at the beginning of the file are now outside the "matches" section. The latter is a minor annoyance and aligns with existing behavior where comments at the beginning of the declaration section are outside the "declarations" node. Fixes #41.

### CODE REVIEW

**Comment by wolfmanstout** [comment]
@wenkokke Please let me know if this makes sense to you. It seems much cleaner to me but it does impact the output slightly.

**Comment by pokey** [comment]
Probably related: https://github.com/wenkokke/tree-sitter-talon/issues/36

**Comment by wolfmanstout** [comment]
Copying these notes from my Slack DM chat with @wenkokke for posterity:

So I’m guessing the reason you did the scanner stuff for the match section in the first place is you were having trouble getting the right parse otherwise. The parser would assume it was looking at commands and then hit an error at some point, apparently unwilling to backtrack.
[8:18](https://talonvoice.slack.com/archives/D0622B0RBGE/p1698592732872869)
This is what I saw when I tried it. But I know that the parser is supposed to be able to handle any grammar so it ought to be able to backtrack this.
[8:19](https://talonvoice.slack.com/archives/D0622B0RBGE/p1698592761193969)
As it turns out the problem wasn’t parser backtracking, it was lexer backtracking.
[8:20](https://talonvoice.slack.com/archives/D0622B0RBGE/p1698592823698749)
Every unique expression in the grammar gets assigned a token and it does lexing interleaved with parsing, intelligently based on what tokens are possible given the current parse.
[8:20](https://talonvoice.slack.com/archives/D0622B0RBGE/p1698592859024799)
There were a couple expressions that were different in the grammar but could match the same underlying token string.
[8:21](https://talonvoice.slack.com/archives/D0622B0RBGE/p1698592880675549)
So because it had a particular parse in mind, it picked the wrong token.
[8:22](https://talonvoice.slack.com/archives/D0622B0RBGE/p1698592960611809)
I fixed this by introducing a new expression in the grammar that matches the set of tokens that are the intersection of those two ambiguous expressions. In effect that also introduced a new token, and it meant that when the parser needed to backtrack, it wasn’t held back by its earlier choice of token.
[8:23](https://talonvoice.slack.com/archives/D0622B0RBGE/p1698593021406719)
So TL/DR if you run into issues in the future where it doesn’t want to backtrack, look at what token the two diverge at and make sure it’s not ambiguous.
[8:23](https://talonvoice.slack.com/archives/D0622B0RBGE/p1698593038520069)
I introduced the new token towards the top of the grammar because those take precedence
[8:25](https://talonvoice.slack.com/archives/D0622B0RBGE/p1698593106908439)
I didn’t set a strong precedence because the other heuristics like “match the longest tokens possible” are still what I want.
[8:25](https://talonvoice.slack.com/archives/D0622B0RBGE/p1698593116814139)
There’s a section describing these rules in the docs:
[8:25](https://talonvoice.slack.com/archives/D0622B0RBGE/p1698593153471979)
https://tree-sitter.github.io/tree-sitter/creating-parsers#lexical-precedence-vs-parse-precedence
[8:26](https://talonvoice.slack.com/archives/D0622B0RBGE/p1698593198032939)
https://tree-sitter.github.io/tree-sitter/creating-parsers#lexical-analysis
  [8:38 AM](https://talonvoice.slack.com/archives/D0622B0RBGE/p1698593882996009)
I think there are lots of benefits to avoiding custom lexer code if you can. In this case, the lexer was emitting a zero length token, which is discouraged as it can trigger infinite loop bugs, for example. It also had to essentially re-implement stuff that can be easily handled at the parser layer, like looking for one or more dashes. (edited)

**Comment by wenkokke** [comment]
Merged and published in v4!

**Comment by wolfmanstout** [comment]
Woo hoo, thanks!

**Pull request merged**
