### PR TITLE
Added support for deck declaration

### PR DESCRIPTION
**Pull request by AndreasArvidsson**

### CODE REVIEW

**Comment by AndreasArvidsson** [comment]
@wenkokke Thank you. Is a new release done automatically? If not can you let me know when you have a new version available?

@pokey are you available to help me with a new release of the parse tree extension?

**Comment by wenkokke** [comment]
It's not done automatically. I have to trigger a version bump.

**Comment by pokey** [comment]
this is now released in vscode-parse-tree 0.31.0

**Comment by AndreasArvidsson** [comment]
Tested and appears to be working!

**Pull request merged**
